### ISSUE TITLE
Pull requests missing

### ISSUE THREAD

**Issue by RafalSkolasinski** [github-changelog-generator/github-changelog-generator#971]
**Describe the bug**

We recently noticed that in latest releases of our [Seldon Core](https://github.com/SeldonIO/seldon-core/) the `Merged pull requests` section is missing. 

**To Reproduce**

Full changelog with missing pull requests for releases 1.8 and 1.9 is [here](https://github.com/SeldonIO/seldon-core/blob/master/CHANGELOG.md). 

1. Clone seldon-core
2. Checkout master
3. Execute 
```
docker run --rm -it -v $(pwd):/work -w /work ruby bash -c 'gem install github_changelog_generator && bash'
    github_changelog_generator -u seldonio --token [github api token here to avoid limits] --project seldon-core
```
4. See lots of errors of form
```
Warning: PR 3222 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3217 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3211 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3209 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3205 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3203 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3200 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3193 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3191 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3188 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3183 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3172 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3171 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3166 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3163 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3160 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3159 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3155 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3153 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3152 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3151 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3147 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3142 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3141 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3135 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3134 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3123 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3118 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3117 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3116 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3110 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3104 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3101 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3099 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3095 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3094 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3093 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3092 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3090 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3089 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3088 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3086 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3085 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3083 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3082 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3081 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3078 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3076 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3074 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3060 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3055 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3048 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3044 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 3014 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2959 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2955 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2920 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2917 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2895 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2742 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2740 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2270 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 2268 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 1795 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 659 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
```

**Expected behavior**

No errors and pull requests always included. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker on Ubuntu 20.04
 - Browser [Chrome but N/A]
 - Version [20.04]

**Additional context**

**Comment by axsaucedo** [comment]
+1 

Would be great if there are any insights on how to fix this

**Comment by YarikTH** [comment]
I have a similar issue in https://github.com/YarikTH/ureact when tried to use this generator. And it seems that I found the root of at least my problem. It's because I started to merge PR using rebase. It seems that the changelog-generator doesn't know how to handle this, so it ignores PRs and emits a warning.

Note: I tried to use changelog-generator for the first time, so I have nothing to compare.

**Comment by RafalSkolasinski** [comment]
Have this been by any chance confirmed by the authors? @skywinder @olleolleolle

**Comment by cyberw** [comment]
+1

Only seems to happen for our most recent PR:s. The PR merged *before* the error appears has a lot of force pushes (https://github.com/locustio/locust/pull/1805), but other than that I dont know what could be causing this.

```
github_changelog_generator -t ... -u locustio -p locust --exclude-labels duplicate,question,invalid,wontfix,cantfix,stale --future-release 2.0.0b2
...
Filtered issues: 798
Fetching events for issues and PR: 1218
Fetching closed dates for issues: 1218/1218
Warning: PR 1811 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 1809 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Associating PRs with tags: 420/420
Generating entry...
Done!
```

**Comment by cyberw** [comment]
Huh. It started working for me again. Maybe after I tagged master?

**Comment by RafalSkolasinski** [comment]
@cyberw Tagged master? If you would be able to identify what makes it work / not work we would be super keen to try it on our end right away :)

**Comment by cyberw** [comment]
That's really the only thing I changed. I even pushed a commit to master (https://github.com/locustio/locust/commit/61b3c2808832c2735cbe17da69004a2787ca2eaf) but that didnt seem to do anything. But once I tagged it with 2.0.0b2 (created a release in GH web UI) it started working.

**Comment by RafalSkolasinski** [comment]
Oh, you mean that the release tag should be included in the `master` branch? 
I do believe that we have release tags on the release branches... Maybe that is the issue.

**Comment by cyberw** [comment]
I dont think my issue relates to the tagging itself (I dont think I've had to tag before creating the changelog before? I'm using the --future-release param), I think it just made something refresh or work differently when there was a new tag.

**Comment by cyberw** [comment]
Before tagging:
```
Found 63 tags
Fetching tags dates: 63/63
Sorting tags...
Received issues: 1771
Pull Request count: 636
Filtered pull requests: 420
Filtered issues: 798
Fetching events for issues and PR: 1218
Fetching closed dates for issues: 1218/1218
Warning: PR 1811 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 1809 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Associating PRs with tags: 420/420
Generating entry...
Done!
Generated log placed in /Users/lafp/git/locust/CHANGELOG.md
```
After tagging:
```
Found 64 tags
Fetching tags dates: 64/64
Sorting tags...
Received issues: 1771
Pull Request count: 636
Filtered pull requests: 420
Filtered issues: 798
Fetching events for issues and PR: 1218
Fetching closed dates for issues: 1218/1218
Associating PRs with tags: 420/420
Generating entry...
Done!
Generated log placed in /Users/lafp/git/locust/CHANGELOG.md
```

**Comment by cyberw** [comment]
Maybe the core issue is "not found in the release branch"? Those merge commits should definitely be in the release branch (master), but maybe the tag helped changelog generator find it?

**Comment by cyberw** [comment]
The more I think about it, the more that makes sense: It seems PR:s made after the last tag arent found.

**Comment by cyberw** [comment]
Yup, and now I merged another PR (without adding a tag), and the error is back (for that PR).

```
github_changelog_generator -t ... -u locustio -p locust --exclude-labels duplicate,question,invalid,wontfix,cantfix,stale --future-release 2.0.0b3

Using these options:
:date_format=>"%Y-%m-%d"
:output=>"CHANGELOG.md"
:base=>"HISTORY.md"
:issues=>true
:add_issues_wo_labels=>true
:add_pr_wo_labels=>true
:pulls=>true
:filter_issues_by_milestone=>true
:issues_of_open_milestones=>true
:author=>true
:unreleased=>true
:unreleased_label=>"Unreleased"
:compare_link=>true
:exclude_labels=>["duplicate", "question", "invalid", "wontfix", "cantfix", "stale"]
:summary_labels=>["Release summary", "release-summary", "Summary", "summary"]
:breaking_labels=>["backwards-incompatible", "Backwards incompatible", "breaking"]
:enhancement_labels=>["enhancement", "Enhancement", "Type: Enhancement"]
:bug_labels=>["bug", "Bug", "Type: Bug"]
:deprecated_labels=>["deprecated", "Deprecated", "Type: Deprecated"]
:removed_labels=>["removed", "Removed", "Type: Removed"]
:security_labels=>["security", "Security", "Type: Security"]
:configure_sections=>{}
:add_sections=>{}
:issue_line_labels=>[]
:max_issues=>nil
:simple_list=>false
:ssl_ca_file=>nil
:verbose=>true
:header=>"# Changelog"
:merge_prefix=>"**Merged pull requests:**"
:issue_prefix=>"**Closed issues:**"
:summary_prefix=>""
:breaking_prefix=>"**Breaking changes:**"
:enhancement_prefix=>"**Implemented enhancements:**"
:bug_prefix=>"**Fixed bugs:**"
:deprecated_prefix=>"**Deprecated:**"
:removed_prefix=>"**Removed:**"
:security_prefix=>"**Security fixes:**"
:http_cache=>true
:require=>[]
:config_file=>".github_changelog_generator"
:token=>"hidden value"
:user=>"locustio"
:project=>"locust"
:future_release=>"2.0.0b3"

Found 64 tags
Fetching tags dates: 64/64
Sorting tags...
Received issues: 1773
Pull Request count: 637
Filtered pull requests: 421
Filtered issues: 799
Fetching events for issues and PR: 1220
Fetching closed dates for issues: 1220/1220
Warning: PR 1777 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Associating PRs with tags: 421/421
Generating entry...
Done!
Generated log placed in /Users/lafp/git/locust/CHANGELOG.md
```

**Comment by cyberw** [comment]
Can you reproduce it? I'm kind of in a catch 22 situation, because I need to update the changelog _before_ tagging (because tagging is what starts my package upload), and I right now I cant do that :)

**Comment by bastelfreak** [comment]
Hi,
I can reproduce this with all repos I tried from the voxpupuli github org, for example https://github.com/voxpupuli/beaker/pull/1711. This worked fine in the past. I tried downgrading github-changelog-generator  but I get the same error on 1.16.3, 1.16.2 and 1.16.1. I also downgraded octokit to 4.20.0. All without luck. Maybe something in the github api changed? or one of the other dependencies?

**Comment by bastelfreak** [comment]
I've another repository with the same issue: https://github.com/puppetlabs/puppet-lint/pull/13

**Comment by bastelfreak** [comment]
I can also reproduce the issue from https://github.com/voxpupuli/beaker/pull/1711 with the latest docker container:
```
$ docker run -it --rm -v "$(pwd)":/usr/local/src/your-app githubchangeloggenerator/github-changelog-generator --user voxpupuli --project beaker --future-release 4.30.1 -t *** --release-branch master --no-http-cache
Using these options:
:date_format=>"%Y-%m-%d"
:output=>"CHANGELOG.md"
:base=>"HISTORY.md"
:issues=>true
:add_issues_wo_labels=>true
:add_pr_wo_labels=>true
:pulls=>true
:filter_issues_by_milestone=>true
:issues_of_open_milestones=>true
:author=>true
:unreleased=>true
:unreleased_label=>"Unreleased"
:compare_link=>true
:exclude_labels=>["duplicate", "question", "invalid", "wontfix", "Duplicate", "Question", "Invalid", "Wontfix", "Meta: Exclude From Changelog"]
:summary_labels=>["Release summary", "release-summary", "Summary", "summary"]
:breaking_labels=>["backwards-incompatible", "Backwards incompatible", "breaking"]
:enhancement_labels=>["enhancement", "Enhancement", "Type: Enhancement"]
:bug_labels=>["bug", "Bug", "Type: Bug"]
:deprecated_labels=>["deprecated", "Deprecated", "Type: Deprecated"]
:removed_labels=>["removed", "Removed", "Type: Removed"]
:security_labels=>["security", "Security", "Type: Security"]
:configure_sections=>{}
:add_sections=>{}
:issue_line_labels=>[]
:max_issues=>nil
:simple_list=>false
:ssl_ca_file=>nil
:verbose=>true
:header=>"# Changelog"
:merge_prefix=>"**Merged pull requests:**"
:issue_prefix=>"**Closed issues:**"
:summary_prefix=>""
:breaking_prefix=>"**Breaking changes:**"
:enhancement_prefix=>"**Implemented enhancements:**"
:bug_prefix=>"**Fixed bugs:**"
:deprecated_prefix=>"**Deprecated:**"
:removed_prefix=>"**Removed:**"
:security_prefix=>"**Security fixes:**"
:http_cache=>false
:require=>[]
:config_file=>".github_changelog_generator"
:user=>"voxpupuli"
:project=>"beaker"
:future_release=>"4.30.1"
:token=>"hidden value"
:release_branch=>"master"

Found 209 tags                                                         
Fetching tags dates: 209/209
Sorting tags...
Received issues: 1710                                                  
Pull Request count: 1573                                               
Filtered pull requests: 1315
Filtered issues: 137
Fetching events for issues and PR: 1452                                
Fetching closed dates for issues: 1452/1452
Warning: PR 1714 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 1604 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 1276 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 939 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 352 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Associating PRs with tags: 1315/1315
Generating entry...
Done!
Generated log placed in /usr/local/src/your-app/CHANGELOG.md
 $
```

The listed PRs were merged into master / the release branch:
* https://github.com/voxpupuli/beaker/pull/1714

The following indeed not:
* https://github.com/voxpupuli/beaker/pull/1604
* https://github.com/voxpupuli/beaker/pull/1276
* https://github.com/voxpupuli/beaker/pull/939
* https://github.com/voxpupuli/beaker/pull/352

**Comment by ZedThree** [comment]
I'm seeing this in https://github.com/boutproject/BOUT-dev, except that `github_changelog_generator` _can_ fetch closed PRs for the previous tag. That is, the latest tag is v4.3.2 and PRs merged since then aren't fetched, but PRs merged between v4.3.1 and v4.3.2 _are_.

I'm running like:
```
github_changelog_generator -u boutproject -p BOUT-dev --no-issues --future-release v4.3.3 --release-branch master --since-tag v4.3.1
```

Running like:

```
github_changelog_generator -u boutproject -p BOUT-dev --no-issues-wo-labels --future-release v4.3.3 --release-branch master --since-commit 2020-10-21
```
fetches the closed issues, but removes all of the merged PRs from the changelog.

**Comment by RafalSkolasinski** [comment]
Do we have any update on this maybe? A chance that it could be fixed in the upstream or some sort of FAQ added with an official workaround?

**Comment by cyberw** [comment]
> For those of you seeing this issue, is it happening when your release branch is not the repository's default branch? If so, then #979 should fix it for you once merged / released

Unfortunately this is happening on master branch for me.

**Comment by kian2attari** [comment]
+1 Same here...we are encountering the error even though we are releasing on the default branch

**Comment by axsaucedo** [comment]
+1 for us, it's happening on our default branch

**Comment by cyberw** [comment]
@olleolleolle Any insights? I'm going to try installing latest master to see if @pokey 's fix makes any difference (although it probably wont)

**Comment by bastelfreak** [comment]
with https://github.com/github-changelog-generator/github-changelog-generator/pull/979 being merged I tried this again on https://github.com/voxpupuli/beaker. It still fails:

```
$ bundle exec rake changelog
Found 209 tags
Fetching tags dates: 209/209
Sorting tags...
Received issues: 1713
Pull Request count: 1576
Filtered pull requests: 1311
Filtered issues: 134
Fetching events for issues and PR: 1445
Fetching closed dates for issues: 1445/1445
Warning: PR 1691 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 1604 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 1276 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 939 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 352 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Associating PRs with tags: 1311/1311
Generating entry...
Done!
Generated log placed in /home/bastelfreak/code/beaker/CHANGELOG.md
```

to reproduce:
* git clone https://github.com/voxpupuli/beaker.git
* export CHANGELOG_GITHUB_TOKEN=...
* adjust version in Gemfile
* bundle exec rake changelog

It doesn't matter if I switch to a new branch or run this on master.

**Comment by cyberw** [comment]
Does anyone have time to take a look? Maybe @ferrarimarco ? This is a show stopper for a lot of people.

**Comment by pokey** [comment]
@cyberw I'm currently experimenting with using [release-drafter](https://github.com/release-drafter/release-drafter) instead

**Comment by sanketsudake** [comment]
Facing the same issue on the master branch for https://github.com/fission/fission

All PRs apart from master from the last tagged release not reflecting in the changelog.

https://github.com/fission/fission/blob/master/hack/changelog.sh

**Comment by cyberw** [comment]
Still no word from @olleolleolle or any other maintainers?

**Comment by bastelfreak** [comment]
hey. I did some poking on the codebase. I can still reproduce this issue but I'm unable to track it down :( Has anyone some ideas here?

**Comment by ben-xD** [comment]
As a workaround, I created a temporary new tag (e.g. `temp-tag`) on the release branch (in my case, it's called `main`, which is also the default branch). Then, I re-ran the command to the previous release tag I wanted (e.g. v1.2.5).

Then I ran the command it worked. I then deleted the tag locally and in github, to clean things up again.

**Comment by bastelfreak** [comment]
Hi people. This still happens with the latest master branch of github-changelog-generator. I cannot push a temporary tag to GitHub because that would automatically release it. Has someone else an idea what's happening here?

**Comment by dooleyb1** [comment]
Experiencing this exact same thing, pushing temporary tags doesn't even do the job for me.

**Comment by aperezDKT** [comment]
I'm having this issue right now, does a fix has been found for this ?

**Comment by eike-hass** [comment]
For us the issue is resolved with the latest master branch. We just needed to figure out how build an docker image. Any chance of an official release soonish?

**Comment by bastelfreak** [comment]
for my [projects](https://github.com/voxpupuli/beaker) it's still broken, even with the latest master branch of github-changelog-generator. We generate the changelog on our master branch, not a specific release branch.

**Comment by cyberw** [comment]
Spam ping @bruce-szalwinski @olleolleolle @skywinder :)

**Comment by cyberw** [comment]
I'm still dreaming of a fix @olleolleolle @skywinder :)

**Comment by jotoeri** [comment]
My impression is, that the changelog_generator somehow jumps between the branches. Is that possible??

I attached a screenshot from GitKraken on repo nextcloud/forms. In the middle, there are the two commits called "Fix upgrading", of which one was done towards master and then ported to the `stable2` branch.
I will now release from `master`, so ghcg should recognize `#1212` and then continue with `#1209 - #1208 - #1205 - #1204 - ...`.
Instead, ghcg starts from there on to not recognize the PRs anymore with the already known message. So my impression is, that ghcg would jump on the similar commits "Fix upgrading" into the `stable2` branch and continues there. And of course - on `stable2`, there won't be merge commits for `#1209 - #1208 - #1205 - #1204 - ...`.

This just as a guess from investigating. Not sure, if that mechanism could happen with how ghcg works. 🤷‍♂️ 

```
Warning: PR 1205 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
Warning: PR 1204 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
```
![grafik](https://user-images.githubusercontent.com/47433654/192611645-e9dc3c63-d402-4dcf-b5da-48c690d506ce.png)

**Comment by cyberw** [comment]
I added and then immediately removed a tag on my master branch and it worked. The tag was not even after the last merge, but still managed to trigger the inclusion of all all PRs. Kind of a bad workaround, but still a workaround.

**Comment by MartyEwings** [comment]
Folks @bruce-szalwinski @olleolleolle @skywinder  this bug has finally got to the point were working around it is more work than making a change log by had, and we are looking at alternates

**Comment by conbmat** [comment]
any help for this issue, @bastelfreak 

 Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more information on how to upgrade.
 (called from block in initialize at /var/lib/gems/3.0.0/gems/activesupport-7.1.3.2/lib/active_support/cache.rb:327)
Found 30 tags
Fetching tags dates: 30/30
Sorting tags...
Received issues: 185
Pull Request count: 185
Filtered pull requests: 153
Filtered issues: 0
Fetching events for issues and PR: 153
Fetching closed dates for issues: 153/153
Warning: PR 115 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found
/var/lib/gems/3.0.0/gems/github_changelog_generator-1.16.4/lib/github_changelog_generator/generator/generator_fetcher.rb:86:in `block in associate_tagged_prs': No merge sha found for PR 115 via the GitHub API (StandardError)
        from /var/lib/gems/3.0.0/gems/github_changelog_generator-

**Comment by bastelfreak** [comment]
I'm not the maintainer here, just a user. And I wasn't able to fix it for the beaker repo I linked above :(

**Comment by axsaucedo** [comment]
Thanks!
